steps:
  integrationArtifactUpload:
    cpiApiServiceKeyCredentialsId: roverpocServiceKeyCred
    integrationFlowId: Receive_B2C_Customer_Replication_Confirmation_in_SAP_Commerce_Cloud   
    integrationFlowName: 'Notify B2C Customer Replication to SAP Commerce Cloud'
    packageId: SAPCustomerDataCloudIntegrationwithSAPCloudPlatformMasterDataforBusinessPartnersincludingSAPCommerceCloudAdaptations
    filePath: 'Notify B2C Customer Replication to SAP Commerce Cloud.zip'
